### ISSUE TITLE
Develop a Code Management Plan

### ISSUE THREAD

**Issue by DanPatten** [SPDX-Git/SPDX-Git-Scanner#15]
Develop roles and weekly schedule based on issues and requirements for milestones.

**Comment by Kazzira** [comment]
#### Update:
First draft is finished.  Let me know what else is needed or not needed.

**Comment by DanPatten** [comment]
Completed on Wiki

**Comment by DanPatten** [comment]
It looks like we made a communication management plan instead of a code management plan. I moved the WiKi page we made and we need to develop a new code management plan.

**Comment by Kazzira** [comment]
First Draft complete.  Closing issue.


Reopen the issue if you believe there is more to be added and/or if I have missed something important.
