### ISSUE TITLE
spdxdev cross-team coordination

### ISSUE THREAD

**Issue by ttgurney** [SPDX-Git/SPDX-Git-Scanner#19]
Hey Git team, I know this isn't the proper place to put this but I didn't see any contact information for your team anywhere.

Now that you guys have accounts on the spdxdev server, make sure you coordinate with us ( @klumb @plato360 @dswright1990 and myself ) before making systemwide config changes that could affect our work -- or at least give us a heads up before you do so. We will do the same. Our email addresses are all posted in our README.md for convenience. ( https://github.com/ttgurney/yocto-spdx )

I've just recently wiped out the fossology database on that server and did a fresh install, so it should be in good order.

**Comment by jvosik** [comment]
We'll keep this in mind. Closing to clear out our issue list.
