### ISSUE TITLE
Create Method for doSOCS

### ISSUE THREAD

**Issue by DanPatten** [SPDX-Git/SPDX-Git-Scanner#2]
Create a python method that when called will execute doSOCS and scan a file, placing it into the SPDX database.

The only arguments should be the path to the un-scanned file that needs to be scanned.

**Comment by Kazzira** [comment]
Finshed.  Just pass a dict with { 'packagePath': "unscanned_file_path" } in the dospdx method.

You may pass other parameter as well.  Documentation, for now, is the DoSPDX file.

**Comment by DanPatten** [comment]
Can you upload all of your doSOCS code to /src/doSOCS? Any new code place in /src for now I guess.
