### ISSUE TITLE
Connect GitSPDX.py to DoSOCS.py

### ISSUE THREAD

**Issue by jvosik** [SPDX-Git/SPDX-Git-Scanner#23]
1. Copy the current DoSOCS configuration to a safe location
2. Use regex to update select DoSOCS parameters using values from GitSPDX's config
3. import DoSOCS into GitSPDX
4. Call the DoSOCS.main with proper arguments

**Comment by DanPatten** [comment]
First version of this is done

**Comment by jvosik** [comment]
Closing this. Barring something else coming up, I think this is done. We can open another issue if things need to be changed.
