### ISSUE TITLE
Review self-evaluations of other team members

### ISSUE THREAD

**Issue by jvosik** [SPDX-Git/SPDX-Git-Scanner#25]
Comment when you have completed and I will submit them to Matt.

**Comment by jvosik** [comment]
Complete.

**Comment by Kazzira** [comment]
Finished.  Modified my group coordination answer to also include our meeting time.

**Comment by DanPatten** [comment]
Completed. Close this issue once submitted.

**Comment by jvosik** [comment]
Submitted our evaluations via email.
