### ISSUE TITLE
Unit Test GitSPDX

### ISSUE THREAD

**Issue by Kazzira** [SPDX-Git/SPDX-Git-Scanner#30]
One requirement for Milestone 3 is to include unit testing.  This requirement must be fufilled.  Automate whatever can be automated.

**Comment by DanPatten** [comment]
Moving this to Assignment 4 since its not due yet. But its a good idea to get a headstart on this to make Assignment 4 easier.

**Comment by DanPatten** [comment]
What is the status of this? We need to wrap up the project.

**Comment by Kazzira** [comment]
Finshed and closed
