### ISSUE TITLE
Add defaults to config.txt

### ISSUE THREAD

**Issue by DanPatten** [SPDX-Git/SPDX-Git-Scanner#34]
Defaults for database and fossology path

**Comment by jvosik** [comment]
When you do this, please move all parameters without CHANGE_ME as the value to above the comment:

// +---------------------------------------------------------+
// | Always set the below values to CHANGE_ME before pushing |
// +---------------------------------------------------------+

Assign it to me when you're done, as I would like to have the order of parameters in the README match the order of parameters in the file, and the README is generated by a script.

**Comment by DanPatten** [comment]
Done, ready for change order.

**Comment by jvosik** [comment]
Order has been changed.
