### ISSUE TITLE
README Correction

### ISSUE THREAD

**Issue by germonprez** [SPDX-Git/SPDX-Git-Scanner#36]
Change: 

SPDX-Git-Scanner/doSOCS/src/settings.py to
SPDX-Git-Scanner/src/settings.py

**Comment by jvosik** [comment]
Anyone care if I just remove this step entirely? I recently updated the main script so it can accept DoSOCS parameters and automatically appends them (temporarily) to the settings file, so this may be unnecessary at this point.

**Comment by jvosik** [comment]
Removed step due to reasons in previous comment.
