### ISSUE TITLE
GitSPDX.py doesn't use database username/password I provided during install

### ISSUE THREAD

**Issue by ttgurney** [SPDX-Git/SPDX-Git-Scanner#39]
I ran the `install.sh` script and was prompted for username and password for the SPDX database. I entered the correct username and password, then after `install.sh` completed I went to do a scan...

    ...
    _mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

I checked `config.txt` and saw that the username and password were `root` and some other password than what I specified during install.

My recommendation is to dynamically generate the config.txt file during install, with whatever username and password the user specifies at install time.

**Comment by DanPatten** [comment]
The install.sh script does not use config.txt, that is only used by GitSPDX.py. The mysql username and password is needed to setup the SPDX Database. 

The following line will be executed:
mysql --user=$u --password=$p < SOCSDatabase/SQL/SPDX.sql

**Comment by DanPatten** [comment]
Added during install to modify config.txt
