### ISSUE TITLE
Create Method(s) for Git

### ISSUE THREAD

**Issue by DanPatten** [SPDX-Git/SPDX-Git-Scanner#4]
Create various methods needed to pull down files from a git branch. The arguments vary but include a specific URI to the git branch.

Another needed method related to git is placing the final SPDX back into git at the end of all file scans.

**Comment by jvosik** [comment]
Git interface has been promoted. Pulls down a given repository to a temporary local folder, creates a fake SPDX document, and pushes it back to the repository.
