### ISSUE TITLE
GitSPDX.py runs as a bash script when executed

### ISSUE THREAD

**Issue by ttgurney** [SPDX-Git/SPDX-Git-Scanner#40]
After successful install I tried to execute `GitSPDX.py`:

```
$ ./GitSPDX.py
./GitSPDX.py: line 19: import: command not found
./GitSPDX.py: line 20: import: command not found
./GitSPDX.py: line 21: import: command not found
./GitSPDX.py: line 22: import: command not found
./GitSPDX.py: line 23: import: command not found
./GitSPDX.py: line 24: import: command not found
./GitSPDX.py: line 25: import: command not found
./GitSPDX.py: line 28: import: command not found
./GitSPDX.py: line 29: import: command not found
./GitSPDX.py: line 30: import: command not found
from: too many arguments
./GitSPDX.py: line 33: import: command not found
./GitSPDX.py: line 35: syntax error near unexpected token `('
./GitSPDX.py: line 35: `fileConfig = Config.Config()'
```

`GitSPDX.py` has the execute bit but no shebang line (like `#!/usr/bin/python2`) at the top of the file. This is potentially quite dangerous... on some Linux systems there is a `/usr/bin/import` command installed that will clobber any file specified as an argument to it if run during an X session.

At any rate, I understand the readme file says to invoke like `python GitSPDX.py`, but this is less user friendly (in my humble opinion) than allowing the program to be run directly.

**Comment by DanPatten** [comment]
According to the usage documentation you should run the program using python GitSPDX.py. I agree that ./GitSPDX.py would be a more friendly option but would be an enhancement at this point.

**Comment by DanPatten** [comment]
Feature has been added.
