### ISSUE TITLE
Allow disable of auto-commit/push

### ISSUE THREAD

**Issue by ttgurney** [SPDX-Git/SPDX-Git-Scanner#41]
Just because I want to generate a manifest does not mean I want to commit and push it immediately. Perhaps I want to include it as part of another commit, for example. Would be nice to have a feature allowing disabling of auto-commit/push.

**Comment by DanPatten** [comment]
This is a good idea, will mark as enhancement, but is simple enough,

**Comment by DanPatten** [comment]
Added feature.
