### ISSUE TITLE
Allow scanning of a local repository

### ISSUE THREAD

**Issue by ttgurney** [SPDX-Git/SPDX-Git-Scanner#42]
The program only seems to allow scanning remote repositories... my guess is that the typical use case would be scanning a local repository (though I could be completely wrong since I have not heard this from anyone else). My guess is that this functionality could be added with little extra complexity.

**Comment by DanPatten** [comment]
Not sure how complex this would take to implement depending on how the Git API handles local repositories. This would be an unlikely use case for usage of the tool except for local dev users.

**Comment by DanPatten** [comment]
At this time we do not have a use case for this particular option, depending how the Git API is used this may be a major or minor implementation. At this time, will not implement.
