### ISSUE TITLE
add --help support

### ISSUE THREAD

**Issue by plato360** [SPDX-Git/SPDX-Git-Scanner#45]
the program has a lot of options that can be passed in as command line arguments, adding the option of --help from the command line would be helpful so the user doesn't have to pull up the repo or try to figure it out from the config file.

**Comment by DanPatten** [comment]
This is a good idea, although the Wiki works as an option for now.

**Comment by jvosik** [comment]
There's also the README.txt file in the source directory which lists all the parameters and descriptions.

**Comment by joverkamp** [comment]
Additionally, with the install.sh doing what it does, you almost wouldn't need install instructions if there was a short one-liner at the end of the install script reminding the installer to revise the config.txt. I love how easy your program is to install and get running.

**Comment by jvosik** [comment]
As a group, we've decided this is not needed due to the README and Wiki.
