### ISSUE TITLE
Use additional functionality of DoSOCS

### ISSUE THREAD

**Issue by dswright1990** [SPDX-Git/SPDX-Git-Scanner#50]
There are a few DoSOCS command line flags that you could add to your project like "--CREATOR", "--CREATOR_COMMENT" and "--DOCUMENT_COMMENT" you can view our project (YOCTO-SPDX), to see how we implemented those features.

**Comment by jvosik** [comment]
We're leaving this as a future enhancement. Due to how python expects parameters to be passed, it would be too difficult to add the values associated with these flags. Not impossible, but out of the scope of this project.
