### ISSUE TITLE
git.import error

### ISSUE THREAD

**Issue by nchickinelli** [SPDX-Git/SPDX-Git-Scanner#51]
When I try to run GitSPDX.py I get the error below. I believe I have all prerequisites and the install was successful. Any ideas to what may be causing the error? 

![screen shot 2015-04-17 at 1 18 40 am](https://cloud.githubusercontent.com/assets/7442439/7196915/df56c918-e49f-11e4-90eb-0ccc34534936.png)

**Comment by DanPatten** [comment]
Not sure if this solves your issue or not but you should remove 'python' when calling according to the wiki you should just type


  ./GitSPDX.py branch=xxxx

**Comment by nchickinelli** [comment]
Thanks, my mistake. Tried it without python, as the wiki says, and still get the error. I'll try a few more things.

**Comment by DanPatten** [comment]
Try installing GitPython on your OS.

**Comment by nchickinelli** [comment]
Thanks Dan. That did solve a problem. I referred to the prereqs again and double checked the usage wiki. I'm getting this error bellow. Does this mean that I'm still missing something or that I'm passing the argument incorrectly on the command line? 

![screen shot 2015-04-17 at 1 08 11 pm](https://cloud.githubusercontent.com/assets/7442439/7208851/45e026ca-e509-11e4-89a7-826783f611d2.png)
