### ISSUE TITLE
Specify Folder for SPDXDoc

### ISSUE THREAD

**Issue by joverkamp** [SPDX-Git/SPDX-Git-Scanner#52]
Installation, and configuration for your system went very smoothly.

One enhancement I can think of for your program would be the ability (perhaps through a flag) to denote a folder to place the SPDXDoc into in the branch, whether that folder be pre-existing or if it would need to be created.

That would improve the automation experience further by allowing the user to specify where he needs the documents to go. Great work guys!

**Comment by jvosik** [comment]
I think the script can already place it into an existing folder if you just specify the path as part of the file name. Making it create the folder is easy to add, since I already wrote the function to optionally create paths for the creation of the temporary folder.

**Comment by jvosik** [comment]
I looked into the script and it will already create the directory tree required for the SPDX document. The path just needs to be part of the file name.
