### ISSUE TITLE
Cannot scan individual branch

### ISSUE THREAD

**Issue by joverkamp** [SPDX-Git/SPDX-Git-Scanner#53]
Running "sudo ./GitSPDX.py branch=https://github.com/joverkamp/SPDXHub" works just fine and pushes the SPDX document accordingly to the repository.

Running the program on an individual branch i.e. "https://github.com/joverkamp/SPDXHub/tree/master" results in a repo not found error. 

Is this a bug, or a technical constraint?

**Comment by nchickinelli** [comment]
I ran into the the same issue.

**Comment by DanPatten** [comment]
If you have ever used github before you must specify a branch by using the URI. This should always end with .git.
