### ISSUE TITLE
scan queue 

### ISSUE THREAD

**Issue by nchickinelli** [SPDX-Git/SPDX-Git-Scanner#54]
Probably not within current scope. However, it would be convenient to have the ability to queue up multiple branches for consecutive scans. This might be helpful when doing scans on multiple repos within an organization.

**Comment by DanPatten** [comment]
At this time this is outside the scope of our Use Cases, however this would be possible on some type of cronjob or as specified in our wiki, it could be used as an automatic server and several repos can be queued up.
