### ISSUE TITLE
More descriptive errors.  

### ISSUE THREAD

**Issue by nchickinelli** [SPDX-Git/SPDX-Git-Scanner#55]
If there is a breakdown in the scanning process it would be nice to get more descriptive errors with a suggestion for a fix. Right now, printing out the call stack, can be cryptic if not familiar with the software. If you're able to pin-point which technologies come into play at a possible error point that may be helpful to print out – allowing the user to diagnose problems more quickly.

**Comment by jvosik** [comment]
We can try to improve the descriptions of our own errors, but the problem is a lot of the errors that may be encountered are from DoSOCS. Currently, we can't catch any errors DoSOCS throws, just see that some error happened and display the text to the user.
